### ISSUE TITLE
Is it possible to remove the thing at the beginning of heading?

### ISSUE THREAD

**Issue by srevinsaju** [sweatran/typora-onedark-theme#1]
Thanks for this wonderful OneDark theme. I love using it
But I am curious to know if I could remove this thing
![image](https://user-images.githubusercontent.com/48695438/81504246-e29d7e00-92f0-11ea-970a-5063be995c2e.png)

And make it look like the GitHub markdown file.

**Comment by sweatran** [comment]
Remove the follow lines in `onedark.css`:
```
#write h1:before {
    content: '\00A7  ';
}

#write h2:before {
    content: '\00A7  ';
}
```
P.S. You help me find a missing ";", thanks~

**Comment by srevinsaju** [comment]
Great; thanks a lot; 

Glad I could help :joy:
