### ISSUE TITLE
More padding/margin between headers

### ISSUE THREAD

**Issue by gilbertohasnofb** [sweatran/typora-onedark-theme#10]
Would you perhaps consider adding more padding/margin between headers? Right now they are barely separated at all (other than by the use of horizontal rules).

**Comment by sweatran** [comment]
Thank you for your suggestion. 

Although for me I prefer the previous tighter one, I still added a little bit more padding to the headers in the latest release. I think most people may prefer a much looser style. However I still preserved the horizontal rules. 

If you have any more ideas or suggestions, please leave a comment.
