### ISSUE TITLE
Code words wrapped in backticks should not get space at start of lines

### ISSUE THREAD

**Issue by gilbertohasnofb** [sweatran/typora-onedark-theme#11]
Code words wrapped in backticks should not get space at start of lines. E.g.:

```
Lorem ipsum dolor sit amet, consectetur `foobar` adipiscing elit, sed do eiusmod `foobar` tempor incididunt ut labore et dolore magna aliqua. `foobar` Ut enim ad minim  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea  commodo `foobar` consequat.
```

![image](https://user-images.githubusercontent.com/5700795/97812680-e3e5ad00-1c7a-11eb-826e-0d54096302d4.png)

**Comment by sweatran** [comment]
Thank you for your suggestion. There's no extra space before the inline code block anymore in the latest release.

**Comment by gilbertohasnofb** [comment]
@sweatran Great, many thanks for the fix!

Also, just FYI, since your theme is GPL I used it as a base for a new theme of my own, I hope that's all right with you: https://github.com/gilbertohasnofb/typora-panda-theme

And I also used some parts of it in my two other themes, which are dark versions of two default themes:
https://github.com/gilbertohasnofb/typora-gothic-dark-theme
https://github.com/gilbertohasnofb/typora-whitey-dark-theme

**Comment by sweatran** [comment]
@gilbertohasnofb Of course it's Ok! Selecting right elements in Typora is sometimes quite tricky, so please feel free to use some of my codes for convenience.
