### ISSUE TITLE
colored text, ==highlight==

### ISSUE THREAD

**Issue by dongbingliu** [sweatran/typora-onedark-theme#3]
colored text, ==highlight==

不支持

**Comment by sweatran** [comment]
请先检查 `偏好设置 > Markdown > Markdown 扩展语法` 中高亮是否已经启用，该选项默认是不启用的。
如果已经启用，希望您可以提供您的系统信息以及高亮未生效的相关 Markdown 代码。

**Comment by dongbingliu** [comment]
问题已经解决了，谢谢确实是扩展语法没有生效
