### ISSUE TITLE
HTML table display weirdness

### ISSUE THREAD

**Issue by 2b** [sweatran/typora-onedark-theme#6]
Hello!

The HTML tables displayed without any separators. There is no such problem on the default themes. Tested on Windows and MacOS with the same result.

Is there any way to make the HTML tables as glorious as the Markdown ones?

**Night theme:**

![night](https://user-images.githubusercontent.com/829041/92369687-d7b0f980-f0e8-11ea-8541-77762918fe90.png)

**Onedark:**

![onedark](https://user-images.githubusercontent.com/829041/92369749-eb5c6000-f0e8-11ea-8608-1bbfd3f6b432.png)

Example HTML table code (sorry for the code, it's autogenerated):

[html_table.txt](https://github.com/sweatran/typora-onedark-theme/files/5182126/html_table.txt)

**Comment by sweatran** [comment]
Thank you for your feedback! 

The display problem of HTML tables has been fixed in the latest v1.04 release. The HTML tables now has the same display with normal tables in Typora. 

Please check out the new release and leave a comment if it still has any display problem.

**Comment by 2b** [comment]
Wow, so quickly! Thanks a lot, now it's perfect:

![onedark_1 0 4](https://user-images.githubusercontent.com/829041/92384654-fcfd3200-f0ff-11ea-891f-8c28eb508f74.png)
