### ISSUE TITLE
checkbox 默认背景框能设置为白色吗?

### ISSUE THREAD

**Issue by dongbingliu** [sweatran/typora-onedark-theme#7]
checkbox 默认背景框能设置为白色吗?

黑色主题, 看着不明显了

![image](https://user-images.githubusercontent.com/7981299/92717094-45338300-f392-11ea-9b1c-aba0a5af79d7.png)

**Comment by sweatran** [comment]
非常抱歉，本主题旨在尽可能还原 VScode 中 One Dark Pro 主题的配色方案，这里 checkbox 使用了与原主题相同的颜色。因此您只能尝试自行修改主题中的设置。以下是修改方法：

* 修改 css 文件中第 43 行 `--input-color` 的颜色：
  ```
  --input-color: rgb(xxx, xxx, xxx);
  ```
  > 需要注意，修改后输入框、选择框、radio 等控件的颜色也会变为相同的颜色。

* 若只希望修改 checkbox 的颜色，请修改第 436 行的 `background-color`：
  ```
  input[type="checkbox"]:before {
    ...
    background-color: var(--input-color);
    ...
  }
  ```

如还有疑问，请随时留言，我会尽可能为您解答。

**Comment by dongbingliu** [comment]
Thanks♪(･ω･)ﾉ
