### ISSUE TITLE
Are the symbols before headers intentional?

### ISSUE THREAD

**Issue by dp-IED** [sweatran/typora-onedark-theme#8]
I've noticed that there are these weird symbols in front of all headers. Is this intentional because I don't really like it lol. If it is, could you tell me what file I need to edit to get rid of it?

Love the theme btw!

**Comment by sweatran** [comment]
Yes, the symbols in front of h1 and h2 headers are added intentionally, in order to seperate each level of headers much clearly. Otherwise it would be quite confused to distinguish between h1 to h4 only by the font size. It is called section sign.

You can delete the following lines in css file to remove the section signs before the headers:
```
#write h2:before {
  content: "\00A7  ";
}
```
Or, if you want to change that symbol to whatever you like, just replace `\00A7`  with other characters.

**Comment by KaKi87** [comment]
Hello,

> I don't really like it

Me neither.

> it would be quite confused to distinguish between h1 to h4 only by the font size

Is it ? I don't think so.

But even if it is :
- how does the section sign helps as it is identical for `h1` and `h2` and that all of `h4` to `h6` doesn't have any nor any other indicator ?
- wouldn't it be enough to just click on the header and count the sharp signs ?

And if you're still not convinced : how about displaying these on `:hover` ?

Thanks.

**Comment by dp-IED** [comment]
I think he has a point, don't get me wrong I loved the theme but this was really creeping me out so I switched.

**Comment by sweatran** [comment]
@KaKi87 Just calm down. Different people have different opinions about themes. Using this symbol is just my personal preference.

For three questions you asked, these are my thought:
* Using different styles for h1 and h2 is quite common. Even Github will add underlines to h1 and h2, but not to h3~h6. 
* Typora only show sharp signs on source code mode.
* Change the header style on `:hover` is cool. However adding too much animation effect for content display is not what a text editor should do.

However I still decided to remove these section sign in the latest release. My consideration is that adding a sign manually before the headers is much easier than, for someone who is unfamiliar with editing CSS, removing a sign added by CSS. Maybe if I have time, I will write a script or something for others to customize this theme more friendly.

Anyway, thanks for your suggestion.

**Comment by KaKi87** [comment]
> Just calm down.

Sorry I dindn't wanted to look upset, I assure you that I am not :)

Thanks for your consideration !

**Comment by dp-IED** [comment]
I'm not upset at all, it's just that I don't know much css so I was a little frustrated to see that I couldn't use this theme on a daily basis.

Have a good day!

**Comment by KaKi87** [comment]
Can I also suggest using 50% opacity (`rgb(170, 178, 180, 0.5)`) on header bottom borders ?
Thanks

**Comment by sweatran** [comment]
@KaKi87 Yes I tried this just now. A little bit weird at first glance, but after getting used to it, it looks pretty well. 

I changed the color along with some other changes in the v1.07 release, please check it out. 

Thanks for your seggestion! 👍

**Comment by KaKi87** [comment]
Nice release !
Also, would you mind adding version numbers on ZIP names ?
Thanks xD

**Comment by sweatran** [comment]
@KaKi87 Not problem:joy:, I'll add that from the next release.
