### ISSUE TITLE
Really cool theme but has to be turned off when making a Class Diagram in Mermaid(NOooooooo plz)

### ISSUE THREAD

**Issue by Desjajja** [sweatran/typora-onedark-theme#9]
The small numbers called cardinality have a stubborn black color that make itself impossible to be distinguished from the background. That's what it looks like: 

![image](https://user-images.githubusercontent.com/58029489/96717750-8bd8bc00-13d9-11eb-8b33-855713518bfc.png)
**before**

![image](https://user-images.githubusercontent.com/58029489/96717795-a1e67c80-13d9-11eb-8510-2bc8fec7e8cb.png)
**after**

As I am still new to CSS, there's little I can do in fixing it. Really looking forward to your help in improving this tiny imperfection.

**Comment by sweatran** [comment]
Sorry for the late reply. 

In the latest release I fixed quite a lot of display bugs in mermaid, including this issue. Now all kinds of charts and diagrams in mermaid have better display effect. 

Please check out the latest release and leave me a comment if you find any bugs.
